const FOODCHECK = {
  title: 'FoodCheck',
  type: 'Bootcamp Project',
  status: 'MVP',
  githubUrl: 'https://github.com/tmansuroglu/Foodcheck',
  demoUrl1: 'https://foodcheck.netlify.app/',
  demoUrl2: '',
  iosUrl: '',
  androidUrl: '',
  goal: 'Creating a quick and easy to use diet tracker.',
  skillsArr: [
    'HTML',
    'CSS',
    'JavaScript',
    'React',
    'Redux',
    'Firebase',
    'Ant Design',
    'Responsive Design',
    'Git',
    'ChartJS',
  ],
};

const JUNIPER = {
  title: 'Juniper',
  type: 'Bootcamp project',
  status: 'MVP',
  githubUrl: 'https://github.com/ReCoded-Org/capstone-istanbul-juniper',
  demoUrl1: 'https://juniper-ist.netlify.app/',
  demoUrl2: '',
  iosUrl: '',
  androidUrl: '',
  goal: 'Teaching middle-eastern youth about environmental problems.',
  // impactArr: [
  //   'Built signature game(memory game) of the project',
  //   "Elevated my teammates' work by organizing off-hour online meetings",
  //   'Became problem solver of the team',
  // ],
  skillsArr: [
    'HTML',
    'CSS',
    'JavaScript',
    'React',
    'Jest',
    'Firebase',
    'Ant Design',
    'Responsive Design',
    'Git',
    'Figma',
    'i18n',
  ],
};

const BIZIM_TARIFLER_WEB = {
  title: 'Bizim Tarifler Web',
  type: 'Professional Team Project',
  status: 'Delivered Project',
  githubUrl: '',
  demoUrl1: 'https://bizimtarifler.com/',
  demoUrl2: '',
  iosUrl: '',
  androidUrl: '',
  goal: 'Combining cooking and ingredient shopping by allowing users to browse recipes through the site and buy ingredients from the partner.',
  // impactArr: ['Hmmm'],
  skillsArr: [
    'HTML',
    'CSS',
    'JavaScript',
    'VueJS',
    'NuxtJS',
    'Sass',
    'Git',
    'Responsive Design',
  ],
};

const BIZIM_TARIFLER_MOBILE = {
  title: 'Bizim Tarifler Mobile',
  type: 'Professional Team Project',
  status: 'Delivered Project',
  githubUrl: '',
  demoUrl1: '',
  demoUrl2: '',
  iosUrl: 'https://apps.apple.com/tr/app/bizim-tarifler/id1358778615?l=en',
  androidUrl:
    'https://play.google.com/store/apps/details?id=com.bizimtarifler.app',
  goal: 'Combining cooking and ingredient shopping by allowing users to browse recipes through the site and buy ingredients from the partner.',
  // impactArr: ['Hmmm'],
  skillsArr: [
    'React Native',
    'React',
    'JavaScript',
    'Git',
    'Responsive Design',
    'Expo',
    'Firebase',
  ],
};

const WIDIO_WEB = {
  title: 'Widio Web',
  type: 'Professional Team Project',
  status: 'Work In Progress',
  githubUrl: '',
  demoUrl1: 'https://widio.com/',
  demoUrl2: '',
  iosUrl: '',
  androidUrl: '',
  goal: 'Creating a property and vehicle sale site in which all ads are based on videos.',
  // impactArr: ['Hmmm'],
  skillsArr: [
    'HTML',
    'CSS',
    'JavaScript',
    'React',
    'NextJS',
    'Redux',
    'Ant Design',
    'Git',
    'Responsive Design',
  ],
};

const ECEM_HAKAN_WEB = {
  title: 'Nutritonist Web Site',
  status: 'MVP - Work In Progress',
  type: 'Professional Project - Solo Project',
  githubUrl: '',
  demoUrl1: 'https://www.ecemhakan.com/',
  demoUrl2: '',
  iosUrl: '',
  androidUrl: '',
  goal: 'Creating a web presence for a nutritionist.',
  // impactArr: ['Hmmm'],
  skillsArr: [
    'HTML',
    'CSS',
    'JavaScript',
    'Vue',
    'NuxtJS',
    'Sass',
    'Bootstrap',
    'Git',
    'Github',
    'Responsive Design',
  ],
};

const PROJECTS_ARR = [
  BIZIM_TARIFLER_WEB,
  BIZIM_TARIFLER_MOBILE,
  WIDIO_WEB,
  ECEM_HAKAN_WEB,
  JUNIPER,
  FOODCHECK,
];

export default PROJECTS_ARR;
