const FOODCHECK = {
  title: 'FoodCheck',
  type: 'Solo Training Project',
  status: 'MVP',
  githubUrl: 'https://github.com/tmansuroglu/Foodcheck',
  demoUrl1: 'https://foodcheck.netlify.app/',
  demoUrl2: '',
  iosUrl: '',
  androidUrl: '',
  goal: 'creating a quick and easy to use diet tracker',
  impactArr: [
    'Took responsibility of whole project when teammate was facing crisis and completed project before its deadline',
  ],
  skillsArr: [
    'HTML',
    'CSS',
    'JavaScript',
    'React',
    'Redux',
    'Firebase',
    'Ant Design',
    'Responsive Design',
    'Git',
    'Github',
    'ChartJS',
    'Routing',
  ],
  responsibilityArr: ['Practicing React'],
};

const JUNIPER = {
  title: 'Juniper',
  type: 'Training Project - Team Project',
  status: 'MVP',
  githubUrl: 'https://github.com/ReCoded-Org/capstone-istanbul-juniper',
  demoUrl1: 'https://juniper-ist.netlify.app/',
  demoUrl2: '',
  iosUrl: '',
  androidUrl: '',
  goal: 'teaching middle-eastern youth about environmental problems through games.',
  impactArr: [
    'Built signature game(memory game) of the project',
    "Elevated my teammates' work by organizing off-hour online meetings",
    'Became problem solver of the team',
  ],
  skillsArr: [
    'HTML',
    'CSS',
    'JavaScript',
    'React',
    'Jest',
    'Firebase',
    'AGILE Methodologies',
    'Ant Design',
    'Responsive Design',
    'Git',
    'Github',
    'Figma',
    'Routing',
    'i18n',
  ],
  responsibilityArr: [
    'Developing a memory game',
    'Code reviewing',
    'Bug bashing',
    'Developing games page',
    'Scrum master for 1 week',
    'Developing twitter section of homepage',
  ],
};

const BIZIM_TARIFLER_WEB = {
  title: 'Bizim Tarifler Web',
  type: 'Professional Project - Team Project',
  status: 'Delivered Project',
  githubUrl: '',
  demoUrl1: 'https://bizimtarifler.com/',
  demoUrl2: '',
  iosUrl: '',
  androidUrl: '',
  goal: 'Combining cooking and ingredient shopping by allowing users to browse recipes through the site and buy ingredients from the partner.',
  impactArr: ['Hmmm'],
  skillsArr: [
    'HTML',
    'CSS',
    'JavaScript',
    'VueJS',
    'NuxtJS',
    'Sass',
    'Git',
    'Github',
    'AGILE Methodologies',
    'Responsive Design',
  ],
  responsibilityArr: ['Bug bashing'],
};

const BIZIM_TARIFLER_MOBILE = {
  title: 'Bizim Tarifler Mobile',
  type: 'Professional Project - Team Project',
  status: 'Delivered Project',
  githubUrl: '',
  demoUrl1: '',
  demoUrl2: '',
  iosUrl: 'https://apps.apple.com/tr/app/bizim-tarifler/id1358778615?l=en',
  androidUrl:
    'https://play.google.com/store/apps/details?id=com.bizimtarifler.app',
  goal: 'Combining cooking and ingredient shopping by allowing users to browse recipes through the site and buy ingredients from the partner.',
  impactArr: ['Hmmm'],
  skillsArr: [
    'React Native',
    'React',
    'JavaScript',
    'Git',
    'Github',
    'AGILE Methodologies',
    'Responsive Design',
    'Bare React Native',
    'Managed Expo',
    'Firebase',
  ],
  responsibilityArr: ['Bug bashing'],
};

const WIDIO_WEB = {
  title: 'Widio Web',
  type: 'Professional Project - Team Project',
  status: 'Work In Progress',
  githubUrl: '',
  demoUrl1: 'https://widio.com/',
  demoUrl2: '',
  iosUrl: '',
  androidUrl: '',
  goal: 'Creating a property and vehicle sale site in which all ads are based on videos',
  impactArr: ['Hmmm'],
  skillsArr: [
    'HTML',
    'CSS',
    'JavaScript',
    'React',
    'NextJS',
    'Redux',
    'Ant Design',
    'Git',
    'Github',
    'AGILE Methodologies',
    'Responsive Design',
  ],
  responsibilityArr: ['Bug bashing'],
};

const ECEM_HAKAN_WEB = {
  title: 'Nutritonist Web Site',
  status: 'MVP - Work In Progress',
  type: 'Professional Project - Solo Project',
  githubUrl: '',
  demoUrl1: 'https://www.ecemhakan.com/',
  demoUrl2: '',
  iosUrl: '',
  androidUrl: '',
  goal: 'Creating a web presence for a nutritionist',
  impactArr: ['Hmmm'],
  skillsArr: [
    'HTML',
    'CSS',
    'JavaScript',
    'Vue',
    'NuxtJS',
    'Sass',
    'Bootstrap',
    'Git',
    'Github',
    'Responsive Design',
  ],
  responsibilityArr: ['Bug bashing'],
};

const PROJECTS_ARR = [
  BIZIM_TARIFLER_WEB,
  BIZIM_TARIFLER_MOBILE,
  WIDIO_WEB,
  ECEM_HAKAN_WEB,
  JUNIPER,
  FOODCHECK,
];

export default PROJECTS_ARR;
